services:
  - type: web
    name: la-maison-des-bluets
    runtime: node
    plan: free
    buildCommand: echo "No build needed"
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
